### ISSUE TITLE
add a sentence or two about workflow? 

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/welcome-to-learn-5-b#1]
we tell students that we're going to practice the workflow of solving labs, but we're not really explaining the "why" of the workfiow. 

After instructions, it might be worth adding a few sentence that explain the super basics of tdd. 
i.e. All programs are composed of different files and folders. Typically we don't just write our code and call it a day but instead we have what we call "tests" which have requirements that our code needs to pass. The first time we run those tests, our code will fail because we haven't done anything yet. Then we update the program with code, run our tests, and see if they pass. This is the workflow developers use and this is the workflow that you'll use to solve your coding labs.

**Comment by aviflombaum** [comment]
Closed by b977616
