### ISSUE TITLE
Error after changing editme file and typing learn command

### ISSUE THREAD

**Issue by jimustri** [learn-co-curriculum/welcome-to-learn-5-b#2]
After making changes to the editme file and saving I typed the 'learn' command and this long error message came up: 
        /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/shellwords.rb:75:in `block in shellsplit': Unmatched double quote: "but you're unable to make the change yourself, you should raise a Github issue" (ArgumentE
rror)                                                                                                  
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/shellwords.rb:73:in`scan'  
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/shellwords.rb:73:in `shellsplit'          
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/shellwords.rb:189:in`shellsplit'  
        from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.2/lib/rspec/core/flat_map.rb:7:in `each
'                                                                                                      
        from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.2/lib/rspec/core/flat_map.rb:7:in`flat
_map'  
        from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.2/lib/rspec/core/flat_map.rb:7:in `flat
_map'

**Comment by AnnJohn** [comment]
hi @jimustri this looks like it's an error specific to you and your environment so could you please use Ask a Question and someone from our team will help you out. Thanks!
